
package com.parameta.SOAPClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISOAPEmpleado", targetNamespace = "http://SOAPServer.parameta.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISOAPEmpleado {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addEmpleado", targetNamespace = "http://SOAPServer.parameta.com/", className = "com.parameta.SOAPClient.AddEmpleado")
    @ResponseWrapper(localName = "addEmpleadoResponse", targetNamespace = "http://SOAPServer.parameta.com/", className = "com.parameta.SOAPClient.AddEmpleadoResponse")
    @Action(input = "http://SOAPServer.parameta.com/ISOAPEmpleado/addEmpleadoRequest", output = "http://SOAPClient.parameta.com/ISOAPEmpleado/addEmpleadoResponse")
    public void addEmpleado(
        @WebParam(name = "arg0", targetNamespace = "")
        Empleado arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.parameta.soapserver.Empleado>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmpleados", targetNamespace = "http://SOAPServer.parameta.com/", className = "com.parameta.SOAPClient.GetEmpleados")
    @ResponseWrapper(localName = "getEmpleadosResponse", targetNamespace = "http://SOAPServer.parameta.com/", className = "com.parameta.SOAPClient.GetEmpleadosResponse")
    @Action(input = "http://SOAPServer.parameta.com/ISOAPEmpleado/getEmpleadosRequest", output = "http://SOAPClient.parameta.com/ISOAPEmpleado/getEmpleadosResponse")
    public List<Empleado> getEmpleados();

}
