
package com.parameta.SOAPClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SOAPEmpleadoImplService", targetNamespace = "http://SOAPServer.parameta.com/", wsdlLocation = "http://localhost:1799/WS/EmpleadoParameta?wsdl")
public class SOAPEmpleadoImplService
    extends Service
{

    private final static URL SOAPEMPLEADOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPEMPLEADOIMPLSERVICE_EXCEPTION;
    private final static QName SOAPEMPLEADOIMPLSERVICE_QNAME = new QName("http://SOAPServer.parameta.com/", "SOAPEmpleadoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1799/WS/EmpleadoParameta?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPEMPLEADOIMPLSERVICE_WSDL_LOCATION = url;
        SOAPEMPLEADOIMPLSERVICE_EXCEPTION = e;
    }

    public SOAPEmpleadoImplService() {
        super(__getWsdlLocation(), SOAPEMPLEADOIMPLSERVICE_QNAME);
    }

    public SOAPEmpleadoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPEMPLEADOIMPLSERVICE_QNAME, features);
    }

    public SOAPEmpleadoImplService(URL wsdlLocation) {
        super(wsdlLocation, SOAPEMPLEADOIMPLSERVICE_QNAME);
    }

    public SOAPEmpleadoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPEMPLEADOIMPLSERVICE_QNAME, features);
    }

    public SOAPEmpleadoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPEmpleadoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISOAPEmpleado
     */
    @WebEndpoint(name = "SOAPEmpleadoImplPort")
    public ISOAPEmpleado getSOAPEmpleadoImplPort() {
        return super.getPort(new QName("http://SOAPServer.parameta.com/", "SOAPEmpleadoImplPort"), ISOAPEmpleado.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISOAPEmpleado
     */
    @WebEndpoint(name = "SOAPEmpleadoImplPort")
    public ISOAPEmpleado getSOAPEmpleadoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SOAPServer.parameta.com/", "SOAPEmpleadoImplPort"), ISOAPEmpleado.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPEMPLEADOIMPLSERVICE_EXCEPTION!= null) {
            throw SOAPEMPLEADOIMPLSERVICE_EXCEPTION;
        }
        return SOAPEMPLEADOIMPLSERVICE_WSDL_LOCATION;
    }

}
